version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_musicpro
    hostname: mysql
    restart: always
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'CcArlos'
      MYSQL_DATABASE: 'musicpro'
      MYSQL_USER: 'userbd'
      MYSQL_PASSWORD: 'passuserbd'
    volumes:
      - ./volumes/data:/var/lib/mysql_musicpro:rw
    networks:
      - mysql_net

networks:
  mysql_net:
    name: api_musicpro
    driver: bridge